### ISSUE TITLE
setUniform, glUniform, glProgramUniform

### ISSUE THREAD

**Issue by ninnghazad** [Ryp/moGL#25]
Is there some rationale behind using glUniform* instead of the DSA-ish glProgramUniform in the setUniform memberfuncs?
Being members i kind of expected the glProgramUniform* funcs to be used and wondered if there was some reason not to do so.

**Comment by ninnghazad** [comment]
well, that's an answer. thanks dude!

**Comment by Ryp** [comment]
No problem, just realizing now that this was a rather large oversight, so fixed that for you!
