### ISSUE TITLE
locations are stored and returned as GLuint instead of GLint

### ISSUE THREAD

**Issue by ninnghazad** [Ryp/moGL#26]
And functions like 
GLuint ShaderProgram::getAttribLocation
GLuint ShaderProgram::getUniformLocation
return these GLuints instead of GLint like the corresponding GL functions.
It's confusing, but most confusing is that the functions return -1 as GLuint upon failure, resulting
in them returning 4294967295 - which is neither a possible location nor a proper failure response.

**Comment by Ryp** [comment]
Thanks for the report
